/*
 * Created on 4 Oct 2017 ( Time 15:33:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.iheartmeadia.POC.controller;

import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.iheartmeadia.POC.model.ResponseMessage;
import com.iheartmeadia.POC.model.TriggerLog;
import com.iheartmeadia.POC.services.TriggerLogService;

@RestController
public class TriggerLogRestController {
	
	private static Logger logger = LoggerFactory.getLogger(TriggerLogRestController.class);
	
	@Autowired
	private TriggerLogService triggerlogService;
		
	/*
	 * READ METHODS
	 */

	@RequestMapping(value="/errors", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getAll() {

		if (logger.isDebugEnabled())
			logger.debug("TriggerLogService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(triggerlogService.findAll());
		} catch (Exception e) {
			logger.error("TriggerLogController -> getAll", e);
			responseMessage.setError(-1, "Unable to get page for TriggerLog: " + e.getMessage());
		}
		return responseMessage;
	}

	@RequestMapping(value="/page", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getPage(@RequestParam int page, @RequestParam int records) {

		if (logger.isDebugEnabled())
			logger.debug("TriggerLogService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(triggerlogService.findAll(page, records));
		} catch (Exception e) {
			logger.error("TriggerLogController -> getPage", e);
			responseMessage.setError(-1, "Unable to get page for TriggerLog: " + e.getMessage());
		}
		return responseMessage;
		
	}


//	@RequestMapping(value="/count", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getCount() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("TriggerLogService -> getAll");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(triggerlogService.count());
//		} catch (Exception e) {
//			logger.error("TriggerLogController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all TriggerLog: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

//	@RequestMapping(value="/page", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getPage(@RequestParam int page,@RequestParam int size) {
//
//		if (logger.isDebugEnabled())
//			logger.debug("TriggerLogService -> getPage(" + page + "," + size + ")");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(triggerlogService.getPage(page, size));
//		} catch (Exception e) {
//			logger.error("TriggerLogController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all TriggerLog: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}
	
//	@RequestMapping(value="/elements", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getDropDownElements() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("TriggerLogService -> getDropDownElements");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(triggerlogService.getDropDownValues());
//		} catch (Exception e) {
//			logger.error("TriggerLogController -> getDropDownElements", e);
//			responseMessage.setError(-1, "Unable to getDropDownElements for TriggerLog: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

	@RequestMapping(value="/{id}", method=RequestMethod.GET,
			produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}, consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
	@ResponseBody
	public ResponseMessage getOne(@PathVariable Integer id) {
		if (logger.isDebugEnabled())
			logger.debug("TriggerLogService -> getOne(" + id + ")");
		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(triggerlogService.get(id));
		} catch (Exception e) {
			logger.error("TriggerLogController -> create", e);
			responseMessage.setError(-1,
					"Unable to create TriggerLog: " + id + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	
	/*
	 * DML Methods
	 */
	@RequestMapping(value = "/create", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage create(@RequestBody TriggerLog element) {

		if (logger.isDebugEnabled())
			logger.debug("TriggerLogService -> create:" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(triggerlogService.create(element));
		} catch (Exception e) {
			logger.error("TriggerLogController -> create", e);
			responseMessage.setError(-1,
					"Unable to create TriggerLog: " + element + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage edit(@PathVariable Integer id, @RequestBody TriggerLog element) {
		if (logger.isDebugEnabled())
			logger.debug("TriggerLogService -> edit(" + id + "):" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			element.setId(id);
			responseMessage.setData(triggerlogService.create(element));
		} catch (Exception e) {
			logger.error("TriggerLogController -> edit", e);
			responseMessage.setError(-1,
					"Unable to edit TriggerLog: " + element + ",Error:" + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value="/delete/{id}", method=RequestMethod.DELETE, 
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage delete(@PathVariable Integer id) {

		if (logger.isDebugEnabled())
			logger.debug("TriggerLogService -> delete(" + id + ")");

		ResponseMessage responseMessage = new ResponseMessage();
		try {
			triggerlogService.delete(id);
		} catch (Exception e) {
			logger.error("TriggerLogController -> delete", e);
			responseMessage.setError(-1, "Unable to delete TriggerLog: " + id + ",Error:"  + e.getMessage());
		}
		return responseMessage;
	}
	
	@ExceptionHandler(Exception.class)
	public @ResponseBody
	String handleException(Exception e, HttpServletResponse response) {
	    response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	    return e.getMessage();
	}

}

