/*
 * Created on 4 Oct 2017 ( Time 15:33:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.iheartmeadia.POC.respositories;

import org.springframework.data.repository.PagingAndSortingRepository;

import com.iheartmeadia.POC.model.TriggerLog;



/**
 * Spring JPA Repository for TriggerLog
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface TriggerLogRepository extends PagingAndSortingRepository<TriggerLog, Integer> {
/*
		TriggerLog findBySfid(String sfid);
*/

}