/*
 * Created on 4 Oct 2017 ( Time 15:33:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.iheartmedia.POC.exceptions;

public class TriggerLogNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public TriggerLogNotFoundException(Integer id) {
		super("TriggerLog not found with id: " + id.toString());
	}

	public TriggerLogNotFoundException(String triggerlog) {
		super("TriggerLog " + triggerlog + " not found!");
	}
}
